# Generated by Django 4.2.26 on 2026-08-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["order", "-date", "title"]},
        ),
        migrations.AddField(
            model_name="project",
            name="architect_consultant",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="project",
            name="built_up_area",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="engineering_highlights",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="scope_of_work",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="project",
            name="sustainability",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name="project",
            name="cover_image",
            field=models.ImageField(blank=True, upload_to="projects/"),
        ),
    ]
