# Generated by Django 4.2.26 on 2026-08-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0002_alter_project_options_project_architect_consultant_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectcategory",
            options={
                "ordering": ["order", "name"],
                "verbose_name_plural": "project categories",
            },
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="project",
            name="engineering_highlights",
            field=models.TextField(
                blank=True, help_text="One highlight bullet per line"
            ),
        ),
    ]
