# Generated by Django 4.2.26 on 2026-08-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newscategory",
            options={
                "ordering": ["order", "name"],
                "verbose_name_plural": "news categories",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["order", "-published_at", "title"]},
        ),
        migrations.AddField(
            model_name="newscategory",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(
                blank=True, default="Technical Office & QA/QC", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="cover_image",
            field=models.ImageField(blank=True, upload_to="news/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
