# Generated by Django 4.2.26 on 2026-08-16 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Job Department",
                "verbose_name_plural": "Job Departments",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                (
                    "location",
                    models.CharField(default="New Cairo, Egypt", max_length=140),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Full-Time", "Full-Time"),
                            ("Part-Time", "Part-Time"),
                            ("Contract", "Contract"),
                        ],
                        default="Full-Time",
                        max_length=40,
                    ),
                ),
                ("experience", models.CharField(default="5-8 Years", max_length=60)),
                ("summary", models.TextField()),
                (
                    "responsibilities",
                    models.TextField(blank=True, help_text="One bullet per line"),
                ),
                ("requirements", models.TextField(help_text="One bullet per line")),
                (
                    "benefits",
                    models.TextField(blank=True, help_text="One bullet per line"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="core.jobdepartment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Opening",
                "verbose_name_plural": "Job Openings",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=140)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=40)),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                ("cover_note", models.TextField(blank=True)),
                ("resume", models.FileField(blank=True, upload_to="resumes/")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="core.jobopening",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Application",
                "verbose_name_plural": "Job Applications",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
