# Generated by Django 4.2.26 on 2026-08-16 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_jobdepartment_jobopening_jobapplication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="years_of_experience",
        ),
    ]
