# Generated by Django 4.2.26 on 2026-08-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_jobapplication_years_of_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="company",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="inquiry_type",
            field=models.CharField(
                choices=[
                    ("tenders", "Tenders & Project Estimations"),
                    ("procurement", "Subcontractors & Supplier Registration"),
                    ("general", "General Inquiries & Client Relations"),
                    ("consulting", "Engineering & Architectural Coordination"),
                    ("other", "Other Inquiries"),
                ],
                default="general",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
