# Generated by Django 4.2.26 on 2026-08-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_contactmessage_company_contactmessage_inquiry_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "who_we_are_title",
                    models.CharField(default="WHO WE ARE", max_length=120),
                ),
                (
                    "who_we_are_p1",
                    models.TextField(
                        default="Albahaa Contracting is an Egyptian joint stock company (S.A.E) with more than 30 years of engineering and contracting experience. Established in 1986, Albahaa began its initial projects under the ownership of Engineer Mohamed Bahaa El Din Abdalla before formally transitioning into a joint stock company on December 14, 2000."
                    ),
                ),
                (
                    "who_we_are_p2",
                    models.TextField(
                        default="As an active member of the Egyptian Federation for Construction and Building Contractors since 1994, Albahaa holds the prestigious Grade A classification in water and sewage infrastructure networks, delivering turnkey civil, residential, and infrastructure landmarks on schedule and within budget."
                    ),
                ),
                (
                    "cta_eyebrow",
                    models.CharField(default="START A PROJECT", max_length=120),
                ),
                (
                    "cta_title",
                    models.CharField(
                        default="Ready to build something iconic?", max_length=160
                    ),
                ),
                (
                    "cta_description",
                    models.TextField(
                        default="Consult with our multidisciplinary engineering teams to bring technical precision and turnkey execution to your next landmark development."
                    ),
                ),
                (
                    "cta_primary_btn_text",
                    models.CharField(default="Contact Our Team", max_length=60),
                ),
                (
                    "cta_primary_btn_url",
                    models.CharField(default="/contact/", max_length=120),
                ),
                (
                    "cta_secondary_btn_text",
                    models.CharField(default="Explore Projects", max_length=60),
                ),
                (
                    "cta_secondary_btn_url",
                    models.CharField(default="/projects/", max_length=120),
                ),
            ],
            options={
                "verbose_name": "About Page Specific Content",
                "verbose_name_plural": "About Page Specific Content",
            },
        ),
        migrations.CreateModel(
            name="AboutStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="e.g. 30+, Grade A, 1994, S.A.E", max_length=30
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. Years of Industry Experience (Est. 1986)",
                        max_length=140,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Company Credential & Stat",
                "verbose_name_plural": "Company Credentials & Stats (About Page)",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CareerPillar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        default="01", help_text="e.g. 01, 02, 03", max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Culture & Value Pillar",
                "verbose_name_plural": "Culture & Values Pillars (Careers Page)",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CareerSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spontaneous_eyebrow",
                    models.CharField(default="SPONTANEOUS APPLICATION", max_length=120),
                ),
                (
                    "spontaneous_title",
                    models.CharField(
                        default="Didn't find the right role for you?", max_length=160
                    ),
                ),
                (
                    "spontaneous_description",
                    models.TextField(
                        default="We are constantly seeking passionate engineers, BIM coordinators, and construction managers. Send your CV and portfolio directly to our recruitment team, and we will contact you when a fitting opportunity opens."
                    ),
                ),
                (
                    "spontaneous_btn_text",
                    models.CharField(default="Send Your CV", max_length=60),
                ),
                (
                    "spontaneous_email",
                    models.EmailField(
                        default="careers@albahaacontracting.com", max_length=254
                    ),
                ),
            ],
            options={
                "verbose_name": "Careers Page Specific Settings",
                "verbose_name_plural": "Careers Page Specific Settings",
            },
        ),
        migrations.CreateModel(
            name="CompanyPillar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        default="01", help_text="e.g. 01, 02, 03", max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Engineering Pillar",
                "verbose_name_plural": "Engineering Pillars (About Page)",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomeContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blueprints_eyebrow",
                    models.CharField(
                        blank=True, default="OUR SPECIALIZATION", max_length=120
                    ),
                ),
                (
                    "blueprints_title_line1",
                    models.CharField(default="WE TURN BLUEPRINTS INTO", max_length=160),
                ),
                (
                    "blueprints_title_line2",
                    models.CharField(default="ENDURING REALITY.", max_length=160),
                ),
                (
                    "blueprints_description",
                    models.TextField(
                        default="With more than three decades of engineering leadership and active membership in the Egyptian Federation for Construction, Al Bahaa delivers turnkey civil, residential, and infrastructure landmarks on schedule, within budget, and to the highest QA/QC standards."
                    ),
                ),
                (
                    "blueprints_btn_text",
                    models.CharField(default="View More", max_length=60),
                ),
                (
                    "blueprints_btn_url",
                    models.CharField(default="/about/", max_length=120),
                ),
                ("blueprints_image", models.ImageField(blank=True, upload_to="home/")),
            ],
            options={
                "verbose_name": "Home Page Specific Content",
                "verbose_name_plural": "Home Page Specific Content",
            },
        ),
        migrations.CreateModel(
            name="PageHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Home Page"),
                            ("about", "About Us Page"),
                            ("projects", "Projects Page"),
                            ("news", "News Page"),
                            ("careers", "Careers Page"),
                            ("contact", "Contact Page"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("eyebrow", models.CharField(blank=True, max_length=140)),
                ("title_line1", models.CharField(blank=True, max_length=160)),
                ("title_line2", models.CharField(blank=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                ("hero_image", models.ImageField(blank=True, upload_to="heroes/")),
            ],
            options={
                "verbose_name": "Page Hero Banner",
                "verbose_name_plural": "Page Hero Banners",
                "ordering": ["page"],
            },
        ),
        migrations.CreateModel(
            name="SpecializationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                (
                    "discipline",
                    models.CharField(default="GRADE A INFRASTRUCTURE", max_length=140),
                ),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Specialization Slide",
                "verbose_name_plural": "Specialization Slides (Home Slider)",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="clientlogo",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Client / Partner Logo",
                "verbose_name_plural": "Client & Partner Logos",
            },
        ),
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact Inquiry",
                "verbose_name_plural": "Contact Inquiries Inbox",
            },
        ),
        migrations.AlterModelOptions(
            name="jobapplication",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "Job Application",
                "verbose_name_plural": "Job Applications Inbox",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceitem",
            options={
                "ordering": ["order", "title"],
                "verbose_name": "What We Do Item",
                "verbose_name_plural": "What We Do Services (About Page)",
            },
        ),
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "Site Settings & Identity",
                "verbose_name_plural": "Site Settings & Identity",
            },
        ),
        migrations.AlterModelOptions(
            name="teammember",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Leadership & Team Member",
                "verbose_name_plural": "Leadership & Team Members",
            },
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "ordering": ["order", "client_name"],
                "verbose_name": "Client Testimonial",
                "verbose_name_plural": "Client Testimonials",
            },
        ),
        migrations.AddField(
            model_name="clientlogo",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="clientlogo",
            name="show_on_about",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="clientlogo",
            name="show_on_home",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="internal_notes",
            field=models.TextField(
                blank=True, help_text="Private internal response notes"
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("unread", "New / Unread"),
                    ("read", "Reviewed"),
                    ("resolved", "Resolved / Contacted"),
                ],
                default="unread",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="internal_notes",
            field=models.TextField(
                blank=True, help_text="Internal HR evaluation notes"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New Application"),
                    ("reviewed", "Under Review"),
                    ("shortlisted", "Shortlisted for Interview"),
                    ("rejected", "Archived / Rejected"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="serviceitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_line1",
            field=models.CharField(
                blank=True, default="Central Hub, Units 213-217", max_length=180
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_line2",
            field=models.CharField(
                blank=True, default="First Settlement, New Cairo, Egypt", max_length=180
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="company_name",
            field=models.CharField(
                default="Al Bahaa Contracting (S.A.E)", max_length=160
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="copyright_text",
            field=models.CharField(
                blank=True,
                default="© 2026 ALBAHAA CONSTRUCTION. ALL RIGHTS RESERVED",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_careers",
            field=models.EmailField(
                blank=True, default="careers@albahaacontracting.com", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_general",
            field=models.EmailField(
                blank=True, default="info@albahaacontracting.com", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_tenders",
            field=models.EmailField(
                blank=True, default="tenders@albahaacontracting.com", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(blank=True, upload_to="branding/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_logo",
            field=models.ImageField(
                blank=True, help_text="Footer brand logo", upload_to="branding/"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_quote",
            field=models.TextField(
                blank=True,
                default="Established in 1986, AlBahaa delivers integrated contracting, finishing, and construction solutions across Egypt.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_quote_author",
            field=models.CharField(
                blank=True, default="Al Bahaa Contracting", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_logo",
            field=models.ImageField(
                blank=True, help_text="Main navbar logo", upload_to="branding/"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="map_directions_url",
            field=models.URLField(
                blank=True,
                default="https://maps.app.goo.gl/wxBbUA5jU5uGwDTZ7",
                help_text="Direct link for Google Maps button",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="map_embed_url",
            field=models.TextField(
                blank=True,
                default="https://maps.google.com/maps?q=30.0633628,31.4215952+(Al+Bahaa+Contracting+-+Central+Hub)&t=&z=16&ie=UTF8&iwloc=&output=embed",
                help_text="Google Maps Embed URL for iframe",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="phone_main",
            field=models.CharField(
                blank=True, default="+20 (2) 2389 9255", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="phone_tenders",
            field=models.CharField(
                blank=True, default="+20 (10) 0123 4567", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="working_hours_emergencies",
            field=models.CharField(
                blank=True,
                default="Friday & Saturday: Site Emergencies Only",
                max_length=140,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="working_hours_weekdays",
            field=models.CharField(
                blank=True,
                default="Sunday – Thursday: 8:00 AM – 5:00 PM",
                max_length=140,
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Detailed biography (especially for founder)"
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="member_type",
            field=models.CharField(
                choices=[
                    ("founder", "Founding Heritage Card"),
                    ("executive", "Executive Board Member"),
                    ("general", "General Team Member"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="is_accent",
            field=models.BooleanField(
                default=False, help_text="Highlight card with dark background"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="show_on_about",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="show_on_home",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="address",
            field=models.TextField(
                blank=True,
                default="Central Hub, Units 213-217, First Settlement, New Cairo, Egypt",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="social_links",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON format, e.g. {'linkedin': 'https://...', 'facebook': 'https://...'}",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=models.ImageField(blank=True, upload_to="team/"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="quote",
            field=models.TextField(blank=True, help_text="Quote or motto"),
        ),
    ]
