# Generated by Django 4.2.26 on 2026-08-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_aboutcontent_aboutstatistic_careerpillar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientlogo",
            name="logo_image",
            field=models.ImageField(blank=True, upload_to="clients/"),
        ),
    ]
