# Generated by Django 4.2.26 on 2026-08-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_clientlogo_logo_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="social_links",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="facebook_url",
            field=models.URLField(
                blank=True,
                default="https://facebook.com",
                help_text="Official Facebook page URL",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="instagram_url",
            field=models.URLField(
                blank=True,
                default="https://instagram.com",
                help_text="Official Instagram page URL",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="linkedin_url",
            field=models.URLField(
                blank=True,
                default="https://linkedin.com",
                help_text="Official LinkedIn page URL",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                default="https://youtube.com",
                help_text="Official YouTube channel URL",
            ),
        ),
        migrations.AlterField(
            model_name="clientlogo",
            name="logo_image",
            field=models.ImageField(
                blank=True,
                help_text="Partner Logo (Transparent PNG or SVG, 1:1 or 4:3)",
                upload_to="clients/",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="blueprints_image",
            field=models.ImageField(
                blank=True,
                help_text="Blueprints section photo (Recommended: 700x900px)",
                upload_to="home/",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="resume",
            field=models.FileField(blank=True, upload_to="resumes/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="pagehero",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Hero banner (Recommended: 1920x1080px, Max 2MB)",
                upload_to="heroes/",
            ),
        ),
        migrations.AlterField(
            model_name="pagehero",
            name="title_line1",
            field=models.CharField(
                blank=True, help_text="Architectural Title Line 1", max_length=160
            ),
        ),
        migrations.AlterField(
            model_name="pagehero",
            name="title_line2",
            field=models.CharField(
                blank=True,
                help_text="Architectural Title Line 2 (Optional)",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text="Browser Favicon (.svg, .png, .ico, .webp)",
                upload_to="branding/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_logo",
            field=models.ImageField(
                blank=True,
                help_text="Footer brand logo (Square SVG or PNG)",
                upload_to="branding/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="header_logo",
            field=models.ImageField(
                blank=True,
                help_text="Main navbar logo (SVG or Transparent PNG)",
                upload_to="branding/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="map_directions_url",
            field=models.URLField(
                blank=True,
                default="https://maps.app.goo.gl/wxBbUA5jU5uGwDTZ7",
                help_text="Direct link for Google Maps directions button",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="map_embed_url",
            field=models.TextField(
                blank=True,
                default="https://maps.google.com/maps?q=30.0633628,31.4215952+(Al+Bahaa+Contracting+-+Central+Hub)&t=&z=16&ie=UTF8&iwloc=&output=embed",
                help_text="Google Maps Embed URL or full <iframe> snippet (auto-sanitized)",
            ),
        ),
        migrations.AlterField(
            model_name="specializationitem",
            name="description",
            field=models.TextField(
                help_text="Detailed engineering capability description"
            ),
        ),
        migrations.AlterField(
            model_name="specializationitem",
            name="discipline",
            field=models.CharField(
                default="GRADE A INFRASTRUCTURE",
                help_text="Primary bold uppercase discipline heading",
                max_length=140,
            ),
        ),
        migrations.AlterField(
            model_name="specializationitem",
            name="title",
            field=models.CharField(
                blank=True, help_text="Full discipline title", max_length=140
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Member photo (Recommended: 600x700px)",
                upload_to="team/",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="quote",
            field=models.TextField(
                blank=True, help_text="Executive quote or vision statement"
            ),
        ),
    ]
